### ISSUE TITLE
[Bug]: Device is not auto selected when coming from interface page for assignment

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox-acls#54]
### NetBox access-list plugin version

1.0.0

### NetBox version

3.2.7

### Steps to Reproduce

1. Go to a device's interface page
2. Click on `Add Access list`
3. Notice that only interface is filled in the drop down

### Expected Behavior

Both device and interface should be pre-filled

### Observed Behavior

Only the interface is pre-filled
![image](https://user-images.githubusercontent.com/5083532/181905250-0cfb3e4a-9e82-4c54-a131-9ed7d5f34790.png)

**Comment by ryanmerolle** [comment]
This is not technically a bug because nothing is broken per say.  The interface is all that maters for the assignment, but I get your point.

The current functionality filters the interface based on the device or vm.

I can look to have it do also set the device based on the interface you select, BUT I was reserving device and virtual_machine filtering on the ACL name and vice versa.  I thought it would be more helpful that if you selected the ACL, it would immediately filter popular the host the ACL is associated to OR if you selected the host it would filter the ACL.  It may be challenging to tackle all iterations.

Maybe if someone more seasoned than I with django or netbox plugins has a suggestion on the approach or a PR, I'd be super interested.

What are your thoughts @abhi1693

**Comment by abhi1693** [comment]
Honestly, all I was looking for the values to be displayed in the form. Sometimes people forget which interface they clicked and came from to be landed on the page. I believe this to be an easy fix to pass `device_id=` or `virtual_machine_id=` along with the current parameters and it will populate the fields. So far, I've not checked the code but I can in a few hours.

**Comment by ryanmerolle** [comment]
Yea agreed.  I should probably open a different issue to filter the host (vm or device) based on ACL, but its not so easy with Generic Foreign Keys.
